[package]
name = "svg_metadata"
version = "0.4.2"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
edition = "2018"
description = "Extracts metadata (like the viewBox, width, and height) from SVG graphics"
license = "Apache-2.0/MIT"
keywords = ["svg", "graphics", "image", "metadata" ]
homepage = "https://github.com/mre/svg-metadata"
categories = [
    "graphics", 
    "multimedia", 
    "parsing"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.14"
regex = "1.3.9"
lazy_static = "1.4.0"
doc-comment = "0.3.3"
